dbt-cta/facebook_marketing/models/1_cta_base/account_report_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/ad_account_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/ad_creatives_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/ad_set_report_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/ad_sets_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/ads_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/ads_insights_overall_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/ads_insights_platform_and_device_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/campaign_report_base.sql, dbt-cta/facebook_marketing/models/1_cta_base/campaigns_base.sql
@emily-flambe This is the change i was thinking. Its the whole replace partitions with todays and yesterdays date with latest data from raw (todays data). What ya think? or should we just make the matviews `full-refresh = True`
=> fix: make sure facebook matviews dont break without full refresh macro

dbt-cta/freshdesk/models/1_cta_base/contact_base.sql, dbt-cta/freshdesk/models/1_cta_base/satisfaction_rating_base.sql, dbt-cta/freshdesk/models/1_cta_base/ticket_base.sql
Alright update on this, I believe the initial failure came from removing the `should_full_refresh` macro the `tickets` base table and matview didnt have the `_airbyte` column so were getting dropped and re-created daily. So this was actually the first time this model tried to run incrementally which didnt work 😢. So with that i decided just to make all incremental streams for freshdesk into full-refresh streams. 
Another finding is that by default the Freshdesk connector pulls data only for the last 30 days of the day its running instead of all available data (which is what the docs say it will do) so I had set a start date on the Airbyte Stream ( i picked 2022-01-01) and reset the stream.
=> fix: make freshdesk incremental models, full-refresh

utils/README.md, utils/init_dbt
@michaelefisher I know there was some reason for adding the `-E` flag to these `sed` commands, but can you remind me what it was? It's causing the script to generate a bunch of backup files, which is something I was hoping we could avoid (see below).
If we need to keep it, I can add a step to remove files with the `-E` suffix, but it would be even cooler for them not to exist?
eg.:
```
spoke_sua_all_campaign_ab1.sql
spoke_sua_all_campaign_ab1.sql-E
spoke_sua_all_campaign_ab2.sql
spoke_sua_all_campaign_ab2.sql-E
spoke_sua_all_campaign_ab3.sql
spoke_sua_all_campaign_ab3.sql-E
...
```
=> feat: init_dbt.sh should not create all those dang backup files

dbt-cta/facebook_marketing/models/3_partner_views/ctam_ads_insights_overall.sql, dbt-cta/facebook_marketing/models/3_partner_views/ctam_ads_insights_platform_and_device.sql, dbt-cta/snapchat_marketing/models/3_partner_views/snapchat_ctam.sql
This is a small thing, but:
When running a sync for the first time, the partner dbt step would always fail first and then succeed, because it was waiting for the matviews to exist in order to create the views. This was always a bit mysterious, since the tables were right there in the `--depends_on:` bit at the top, but I THINK that only works with {{ ref('foo') }}, not with {{ source('bar','foo') }}. Seems arbitrary but what do I know.
=> fix: use 'ref' instead of 'source' to specify model dependencies for partner views

dbt-cta/actblue/models/1_cta_base/_1_cta_base__models.yml, dbt-cta/actblue/models/2_partner_matviews/_2_partner_matviews__models.yml, dbt-cta/packages.yml, utils/README.md, utils/generate_schema_yml.py
This PR adds a python script to automatically generate starter `schema.yml` files for every second-level model directory in a dbt project. This will help is efficiently write tests for our many dbt syncs since we'll just need to add the `test:` dictionaries themselves, as opposed to writing out entire files ourselves.
As a PoC, I generated `schema.yml` config files for our ActBlue sync.
=> Add codegen script to generate `schema.yml` files [DE-182]

dbt-cta/facebook_marketing/models/1_cta_incremental/ad_account_base.sql
The id field in the ad_account_base table starts with act_, so we previously used `right(id, 16)` to strip just the numbers but… apparently ad account IDs can be of varying length!
This PR replaces the `right()` function and `SPLIT`s on the underscore.
=> FIX:  ad account ids are not a fixed length [DE-255]

dbt-cta/usvote_foundation/models/0_ctes/offices_ab1.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_ab2.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_ab3.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_ab1.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_ab2.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_ab3.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_contacts_ab1.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_contacts_ab2.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_contacts_ab3.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_officials_ab1.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_officials_ab2.sql, dbt-cta/usvote_foundation/models/0_ctes/offices_officials_ab3.sql, dbt-cta/usvote_foundation/models/0_ctes/officials_ab1.sql, dbt-cta/usvote_foundation/models/0_ctes/officials_ab2.sql, dbt-cta/usvote_foundation/models/0_ctes/officials_ab3.sql, dbt-cta/usvote_foundation/models/0_ctes/regions_ab1.sql, dbt-cta/usvote_foundation/models/0_ctes/regions_ab2.sql, dbt-cta/usvote_foundation/models/0_ctes/regions_ab3.sql, dbt-cta/usvote_foundation/models/0_ctes/states_ab1.sql, dbt-cta/usvote_foundation/models/0_ctes/states_ab2.sql, dbt-cta/usvote_foundation/models/0_ctes/states_ab3.sql, dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_addresses_base.sql, dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_addresses_contacts_base.sql, dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_base.sql, dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_officials_base.sql, dbt-cta/usvote_foundation/models/1_cta_full_refresh/officials_base.sql, dbt-cta/usvote_foundation/models/1_cta_full_refresh/regions_base.sql, dbt-cta/usvote_foundation/models/1_cta_full_refresh/states_base.sql
These should be specified in the config YAML read by daggy mcdagface, not specified within dbt. (The sync still delivers data successfully, but we want to use the same strat for all our syncs.)
cc @kanelouise - I think these get added in the Airbyte-generated dbt... I wonder if there's a way we can modify the init_dbt.sh script to remove the `schema = ...` lines? If not, then we will need to document somewhere that the person initializing the dbt for a new sync needs to make sure to remove these bits, since it's a very non-obvious step 🤔
=> hotfix: remove schema from configs in USVote Foundation sync

dbt-cta/facebook_marketing/models/1_cta_incremental/_1_cta_incremental__models.yml
These tests were hotfix disabled when deploying to prod, because there were failures on prod data that we didn't experience when running against dev.
There seem to have been some inconsistencies with how airbyte applied date filters across certain models, so there might be records in the `ads` table that don't have corresponding campaigns in the `campaigns` table. To handle this, I've filtered most of the tests on `created_time` to match the airbyte connection settings grabbing data from 2022 and beyond. There are a couple of insights tables that have stats generated for old ads/campaigns (all 0 spend, 0 impressions) and I've filtered those out too.
=> [DE-255] Re-enable Facebook Marketing relationships tests, tweak filter criteria

dbt-cta/dbt_project.yml
We need to override where elementary is trying to write logs from each dbt run. We don't want to write to partner projects, so we add a `database:` param on all elementary models so that we always write to the CTA project.
Post-merge:
=> Fix: route all elementary data to CTA project [DE-200]

dbt-cta/monitoring/models/1_intermediate/pipeline_health/_int_pipeline_health__models.yml
cc @jackwelty, test was failing because "skipped" is a possible status type that we were not allowing 👀 I'm gonna yolo this in, but pls flag if this is in error
=> hotfix: (monitoring) add "skipped" as an allowable status type for int_group_by_invocation_status_type

dbt-cta/monitoring/models/1_intermediate/pipeline_health/int_group_by_invocation_status_type.sql
I just think they're neat!
@jackwelty we should think of a way to surface run-level data in the pipeline health dash - something to give people insight into why models or tests failed, you know? I mean they can always query bigquery, but you know how it is 🤔 
(no need to act on this right now, I'll request this feature via a ticket!)
=> feat: add `message`, `compiled_code` to `int_group_by_invocation_status_type'

utils/universal_tests.yml
This pull request removes the "unique" test from the auto-applied "universal tests" in our schema generation script, since the `_airbyte_ab_id` column is not always unique.
=> [DE-294] airbyte_ab_id is not always unique

dbt-cta/monitoring/models/0_staging/composer_logs/_composer_logs__models.yml, dbt-cta/monitoring/models/0_staging/composer_logs/_composer_logs__sources.yml, dbt-cta/monitoring/models/0_staging/composer_logs/stg_composer_logs__scheduler.sql, dbt-cta/monitoring/models/1_intermediate/composer_logs/_int_composer_logs__models.yml, dbt-cta/monitoring/models/1_intermediate/composer_logs/int_parse_scheduler_logs.sql
This PR adds a set of dbt models in our `monitoring/` project to parse the output of a GCP Log Sink, configured to output a small subset of logs from Composer. The scope of this ticket just called for a POC implementing our absolute base-level metrics, so the result is an intermediate table (`monitoring.int_parse_scheduler_logs`).
In future tickets, we can combine this table with our existing elementary-based logging and any additional logging we need for other metrics into a set of comprehensive reporting tables.
Deployment steps:
=> [DE-296] POC of pipeline health metrics for non-dbt syncs

dbt-cta/monitoring/models/1_intermediate/pipeline_health/_int_pipeline_health__models.yml
We expect `partner_name` and `sync_name` to not be null, because for our Composer-logged-only syncs (i.e. not dbt/DMDF), we join in a metadata sheet. We have a dag ID (`targetsmart_xrefs_sync`) that is not in the sheet, and our nullness rate is hovering right around 5% and occasionally failing the DAG. We should document this sync in our metadata sheet but also bump this threshold.
=> Fix: relax nullness threshold in monitoring pipeline

dbt-cta/monitoring/models/1_intermediate/pipeline_health/_int_pipeline_health__models.yml, dbt-cta/monitoring/models/1_intermediate/pipeline_health/int_group_by_invocation.sql, dbt-cta/monitoring/models/1_intermediate/pipeline_health/int_group_by_run.sql, dbt-cta/monitoring/models/1_intermediate/pipeline_health/int_merge_logs.sql, dbt-cta/monitoring/models/2_reporting/pipeline_health/_rpt_pipeline_health__models.yml, dbt-cta/monitoring/models/2_reporting/pipeline_health/rpt_pipeline_health.sql
This PR creates an `error_message` field in our final reporting table, and surfaces that field in a new viz component on the "Run Listing" page of our PHD ([live in dev](https://lookerstudio.google.com/s/n5BG9nkK1Sg)).
Elementary gives us the dbt error log for every failed invocation, so we just `string_agg()` those together with the model name, and stick all of that in a long string `error_message` field. "Real" debugging should probably take place via Airflow (and we provide all the necessary DAG/run IDs) for this, but this is a quick way for users to get a glimpse at what went wrong for a given run.
=> [DE-289] Add run-level messages

dbt-cta/facebook_marketing/models/1_cta_incremental/_1_cta_incremental__models.yml
FB relationships tests are failing in some cases because foreign keys for some tables are missing corresponding primary keys for older data - for example, there exist some ads_insights_overall rows for ads created in 2022 with ad_ids that have no corresponding `id` in the ads table.
Considering that partners are focusing on 2023 data now, it seems reasonable to reconfigure this test to consider only data with foreign keys in that were created 2023 onwards.
=> fix (facebook_marketing): update relationships test to consider only data 2023 onwards

utils/generate_schema_yml.py
@jitoquinto @kanelouise @royconst per the spooky mystery in [PAD-1799](https://techallies.atlassian.net/browse/PAD-1799), modifying this script to skip partner models for the time being. Will revisit later once we can look into using dbt 1.6.0 (scheduled for July release), which implements official support for materialized view models.
[PAD-1799]: https://techallies.atlassian.net/browse/PAD-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: skip creating schema yamls for partner models [PAD-1799]

utils/dbt_format_utils.py
This tiny modification to the helper function in dbt_format_utils.py makes it so that when you use it to generate matviews for a sync, it will include the field `_airbyte_emitted_at` (whereas previously that field was being excluded along with `_airbyte_ab_id` and `_airbyte_normalized_at`, which we still don't really care about).
`_airbyte_emitted_at` is an important field for us to include in partner materialized views because it enables the partner to see when each row of data was originally synced, which is a specific request we have received.
for viz @kanelouise @jitoquinto @royconst
=> feat: include `_airbyte_emitted_at` in matviews generated from helper script

utils/cta_dbt_helper.sh, utils/universal_tests.yml
Currently the dbt helper script runs generate_schema_yml.py with the `--merge` option assumed, which causes it to fail if there does not already exist a schema yaml.
This PR introduces a couple of user prompts that enable them to run the command with `--merge`, `--overwrite`, or without any options selected (as one does when generating the schema yamls for the first time). The user can additionally specify if the schema yaml should use the "universal tests" in universal_tests.yml.
cc @jitoquinto @royconst @kanelouise
=> feat: enhance cta_dbt_helper.sh to take options when running generate_dbt_tests()

dbt-cta/freshdesk/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
As recorded by this three-part Loom video series (for CTA eyes only, sorry looky-loos!)
[Part 1](https://www.loom.com/share/02ced0dc409048b49643fa1b640fdbfb?sid=f43e3d47-6f99-4883-a13e-a7ebc59cd542)
[Part 2](https://www.loom.com/share/c3c8cf6744864ce28d187555bc9b0ee5?sid=9b2f706c-303f-49b8-99f1-394b22d3b802)
[Part 3](https://www.loom.com/share/e2284d333f0644c391fefee11980ddaf?sid=c3d75a76-b7a8-42d6-a40b-8524c36279e7)
This PR implements the following dbt tests on the Freshdesk base tables:
- `_airbyte_emitted_at` should be a timestamp
- `_airbyte_ab_id` should be unique and not null (this should be true if 1_cta_full_refresh is replacing date partitions as expected, meaning that `min(_airbyte_emitted_at)` should never be smaller than yesterday's date)
- `id` should be unique and not null - …
=> feat (freshdesk): create basic dbt tests [DE-210]

dbt-cta/facebook_marketing/models/0_ctes/ads_insights_platform_and_device_ab5.sql, dbt-cta/facebook_marketing/models/1_cta_incremental/ads_insights_platform_and_device_base.sql
This PR adds a CTE to the models that build ads_insights_platform_and_device so that prior to creating the `_base` table, the `_hashid` values are deduped using only the rows with the most recent `updated_time` values.
We were already using this logic in `ads_insights_overall`, and for whatever reason it wasn't necessary in `ads_insights_platform_and_device` until now, specifically for only one of our partners. But it's clearly a reasonable step to take, and one that we might find we need to add for other models as well. (Of course we could proactively add these CTEs for all of the models, but for now I assume it's better to make the minimal fix and only mess with the rest of the code if this issue crops up elsewhere.)
=> hotfix (FB marketing): add a CTE to dedupe hashids in ads_insights_platform_and_device

dbt-cta/freshdesk/models/0_ctes/conversation_ab3.sql, dbt-cta/freshdesk/models/0_ctes/ticket_ab3.sql, dbt-cta/freshdesk/models/1_cta_full_refresh/conversation_base.sql, dbt-cta/freshdesk/models/1_cta_full_refresh/ticket_base.sql
dbt tests for `id` uniqueness have started failing for `conversation` and `ticket`. These appear to be unwanted dupes originating in the source data, so this PR introduces CTEs that dedupe using only the most recently emitted row for each `id`.
=> hotfix (freshdesk): dedupe on `id` for tables `conversation` and `ticket`

dbt-cta/facebook_marketing/models/1_cta_incremental/ad_set_report_base.sql
This is kind of a special snowflake model - it's an aggregation meant to be used in reporting, which we built into the dbt back when we thought we would be doing this more regularly. As such it doesn't stick to our usual structure of building everything in `0_ctes`, and instead has those CTEs in the 1_cta_incremental model definition itself.
Anyway I added a CTE to dedupe the data in this report on `date_start` and `adset_id`, and also updated the definition of the hashid. Hopefully this avoids duplicate rows in the future?
(dbt tests are passing when run locally, so once this is merged I'll rerun those tasks for the sync in Airflow)
=> hotfix (facebook): dedupe by start_date and adset_id in ad_set_report_base

dbt-cta/google_ads/models/1_partner_incremental/_1_partner_incremental__models.yml
Pretty straightforward since there are only 2 tables we actually deliver in this sync, and the only obvious test to add is to make sure `hashid` is unique. Also added tests for `unique_combination_of_columns` based on the fields that are used to generate the hashid. That _should_ be redundant with the hashid row uniqueness test but I was feeling spicy.
@kanelouise @royconst
=> feat (google ads): add dbt tests [DE-211]

Pipfile, dbt-cta/blocks/models/1_cta_full_refresh/turf_levels_base.sql
Moved turf_levels_base.sql to full_refresh. 
Ran the dbt locally and everything was successful. 
I cleared the failed upstream tests on the dag and marked the run successful. All the tests then passed on the dag.
Incidentally it also fixed the permissions errors that we had a prog lead ticket open for.
=> fix for an issue with turf tables

dbt-cta/bigquery_monitoring/README.md, dbt-cta/bigquery_monitoring/models/1_intermediate/distinct_job_names.sql, dbt-cta/bigquery_monitoring/models/1_intermediate/filtered_logs.sql, dbt-cta/bigquery_monitoring/models/1_intermediate/json_extract_job_details.sql, dbt-cta/bigquery_monitoring/models/2_reporting/job_details.sql, dbt-cta/bigquery_monitoring/models/2_reporting/jobs_with_unnested_tables.sql, dbt-cta/bigquery_monitoring/models/sources.yml, dbt-cta/dbt_project.yml
This will enable us to generate authorized views in partner projects that give them access to reporting views with handy information about queries run in their project. (See accompanying PR in airflow-dags that adds this project to the DMDF config [here](https://github.com/community-tech-alliance/airflow-dags/pull/402))
=> [DE-467] feat: create dbt project for `bigquery_monitoring`

dbt-cta/stackadapt/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml, dbt-cta/stackadapt/models/1_cta_incremental/_1_cta_incremental__models.yml
Some of these tables are nested so do not have `unique` tests for `id` or `_airbyte_ab_id` or some `*_hashid` values. I just set these up so that everything passes when run on VFP's data in prod.
@jitoquinto @kanelouise @royconst could I possibly get 👀 on this somewhat soon so I can merge this in? It's a prerequisite for migrating our prod syncs to k8s airbyte.
=> feat: create dbt tests for StackAdapt

dbt-cta/usvote_foundation/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
Since these are tables that were created from nested fields, the `_airbyte_ab_id` is not unique. Removing that check so tests can succeed.
=> fix: remove uniqueness checks for nested tables on airbyte_ab_id

dbt-cta/action_builder/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
CTA now syncs Action Builder using an Airflow DAG, so in order to run dbt tests on the data using the code in this repository, we need to clear out any tests on columns prefixed `_airbyte_*`, as these no longer exist in the base tables created by the DAG.
=> clean(action_builder): remove tests of `_airbyte_*` fields (deprecated)

dbt-cta/hustle/models/1_cta_incremental/groups_base.sql
major "ope" moment. This PR fixes a bug that was causing us to deliver `goals` data into the `groups` for the Hustle sync. Gonna yolo-merge to resolve DE-517
=> fix (hustle): typo in groups_base [DE-517]

dbt-cta/quickbooks/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
This PR adds uniqueness tests for all `*_hashid` fields (when they are unique per row) and some `id` fields. (Not all tables with `id` use that field as a PK 😐 ). I left out other tests we often include because of the sheer number of tables present - Airflow has a tendency to fail when you give it too many things to do in a single dbt task.
These tests are succeeding when run locally using prod data.
cc @kanelouise @royconst @jitoquinto
=> feat (Quickbooks): add dbt tests [DE-530]

utils/copy_dbt_from_k8s_pod.sh
@michaelefisher I was trying to use copy_dbt_from_k8s_pod.sh (I have my reasons) and this seems like a more straightforward way to check for whether a pod is in a Running state. (Also the code as currently written doesn't work for me - I can't use the existing jsonpath to access the status of a pod, even when I run the command manually in terminal)
However even after fixing(?) this part, I'm still not able to find any dbt files in the running pods. Here's what happens when I run the shell script:
Setting aside the `error from server (BadRequest)`, the list of files the script is attempting to copy doesn't include anything dbt-related. So my next step was to attempt to look around the pod filesystems manually to see if I could find the dbt files. But (predictably) the `config/` folder just …
=> use `jsonpath="{.status.phase}"` to get status of pod

dbt-cta/quickbooks/models/0_ctes/bill_payments_CheckPayment_BankAccountRef_ab1.sql, dbt-cta/quickbooks/models/0_ctes/bill_payments_CreditCardPayment_CCAccountRef_ab1.sql, dbt-cta/quickbooks/models/0_ctes/tax_codes_SalesTaxRateList_TaxRateDetail_ab1.sql
Just a few stragglers were causing dbt to fail when implementing for a new partner.
These dbt commands succeed locally (Quickbooks has a billion models so this is best done one at a time):
```
dbt run --target cta --select bill_payments_CreditCardPayment_CCAccountRef_base
dbt run --target cta --select bill_payments_CheckPayment_BankAccountRef_base
dbt run --target cta --select tax_codes_SalesTaxRateList_TaxRateDetail_base
```
=> fix (quickbooks): missed three Quickbooks model reference replacements

dbt-cta/profiles.yml
This PR ~sets threads in profiles.yml to use an environment variable rather than hardcoded to 4~  adds a profile to `profiles.yml` that uses 1 thread instead of 4. (It would be nice to pass in `threads` as an env var, but jinja templating returns variables as strings, when it needs to be an integer for the dbt to run.)
These changes should be reviewed and merged in tandem with [this PR in airflow-dags](https://github.com/community-tech-alliance/airflow-dags/pull/548), which ~exports that env_var in all DAGs that use dbt~ uses a variable to set the `target` when running dbt on the cta profile, which allows us to set that variable to use the 1-thread profile as desired (currently only for blocks).
=> feat: add new profile that uses 1 thread (for chonker syncs)

dbt-cta/google_analytics_ga4/models/0_ctes/daily_active_users_ab1.sql, dbt-cta/google_analytics_ga4/models/0_ctes/devices_ab1.sql, dbt-cta/google_analytics_ga4/models/0_ctes/four_weekly_active_users_ab1.sql, dbt-cta/google_analytics_ga4/models/0_ctes/locations_ab1.sql, dbt-cta/google_analytics_ga4/models/0_ctes/pages_ab1.sql, dbt-cta/google_analytics_ga4/models/0_ctes/traffic_sources_ab1.sql, dbt-cta/google_analytics_ga4/models/0_ctes/website_overview_ab1.sql, dbt-cta/google_analytics_ga4/models/0_ctes/weekly_active_users_ab1.sql
this succeeds locally - all it does is change the `date` field in the Google Analytics GA4 models to be a DATE type in BQ instead of a string (seems reasonable)
=> hotfix: parse and cast `date` field to date datatype

utils/generate_dbt/templates/0_ctes_ab2.sql
Just a small change to one of the SQL templates used to generate dbt for BQ V2 syncs in order to exclude the field `rownum` from appearing in the final data.
=> hotfix: deduping CTEs should `EXCEPT (rownum)`

utils/generate_dbt/generate_deduping_ctes.py, utils/generate_dbt/templates/0_ctes_ab4.sql
This PR adds a quick and dirty script that iterates through the tables in a project (determined via user input) and generates `0_ctes/TABLE_ab4.sql` files that dedupe rows using the `_hashid` field in each table.
Because this is quick and dirty, the script hardcodes the template being used to generate the SQL, and assumes that the desired filename has the suffix `_ab4`. This should be fine for most or all of our syncs that still do not have these CTEs included, and the main purpose of this script is to facilitate adding those models to existing projects. Future syncs will use `generate_dbt.py` to generate dbt models, and that script already creates deduping CTEs, so this script will no longer be useful once all existing projects have had these models added.
=> feat: new script for generating _ab4 deduping CTEs

dbt-cta/sprout_social/models/0_ctes/facebook_post_analytics_ab1.sql, dbt-cta/sprout_social/models/0_ctes/facebook_profile_analytics_ab1.sql, dbt-cta/sprout_social/models/0_ctes/facebook_profile_analytics_ab2.sql, dbt-cta/sprout_social/models/0_ctes/instagram_post_analytics_ab1.sql, dbt-cta/sprout_social/models/0_ctes/instagram_profile_analytics_ab1.sql, dbt-cta/sprout_social/models/0_ctes/instagram_profile_analytics_ab2.sql, dbt-cta/sprout_social/models/0_ctes/tiktok_post_analytics_ab1.sql, dbt-cta/sprout_social/models/0_ctes/tiktok_profile_analytics_ab1.sql, dbt-cta/sprout_social/models/0_ctes/tiktok_profile_analytics_ab2.sql
These dbt changes accompany recent changes to Sprout Social sync to:
1 - start including `customer_profile_id` in post analytics tables, and 
2 - correctly parse JSON fields in the profile analytics tables.
=> [DE-634] sprout social: add `customer_profile_id` to post analytics and correctly parse json fields in profile analytics

dbt-cta/dbt_project.yml
To test this in dev, I did the following:
1 - ran dbt locally for `partner_a_sprout_social` with full-refresh:
```shell
export CTA_PROJECT_ID='dev3869c056' 
export CTA_DATASET_ID='partner_a_sprout_social'
export PARTNER_DATASET_ID='sprout_social'
export SYNC_NAME=sprout_social
export PARTNER_PROJECT_ID=dev-partner-a-25693fa5
pipenv run dbt run --target cta --select tag:cta --full-refresh
```
2 - confirmed that the matview in dev-partner-a broke as a result:
```sql
SELECT * FROM `dev-partner-a-25693fa5.sprout_social.client_metadata`
```
3 - reran the partner dbt by clearing the [Airflow task in the dev Airflow DAG](https://f9ebbc83f6f3414381d6fa9a52957253-dot-us-central1.composer.googleusercontent.com/log?dag_id=sprout_social&task_id=sprout_social_0_partner_a.dbt_tasks.dbt_sprout_social.dbt …
=> feat: enable `full_refresh` for partner models

dbt-cta/dbt_project.yml
This was a neat idea but it makes the dbt fail if the base table doesn't already exist, and there's no clean way to make it only run if the table already exists. RIP in spaghetti never forgetti
=> fix: remove `TRUNCATE` pre-hook

dbt-cta/blocks_incremental/models/1_cta_full_refresh/address_districts_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/age_to_bin_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/announcements_views_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/ar_internal_metadata_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/campaigns_people_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/campaigns_teams_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/catalist_uploads_registration_forms_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/collections_roles_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/coorganizations_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/delivery_forms_exclusions_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/denominations_organizations_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/denominations_people_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/email_templates_events_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/events_teams_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/list_folders_users_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/lists_people_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/locations_organizations_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/missing_fks_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/organizations_teams_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/projections_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/quality_control_comments_users_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/quality_control_flags_views_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/quality_control_flags_voter_registration_scans_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/scans_qc_overview_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/scheduled_exports_turfs_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/schema_migrations_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/states_base.sql, dbt-cta/blocks_incremental/models/1_cta_full_refresh/voted_labels_base.sql
same change as for all the other full_refresh models in https://github.com/community-tech-alliance/dbt-cta/pull/325 - blocks_incremental got missed/reverted by accident
=> hotfix: replace p6d of date partitions for blocks_incremental

dbt-cta/facebook_pages/models/0_ctes/page_ab2.sql, dbt-cta/facebook_pages/models/0_ctes/page_insights_ab2.sql, dbt-cta/facebook_pages/models/0_ctes/post_ab2.sql, dbt-cta/facebook_pages/models/0_ctes/post_insights_ab2.sql, dbt-cta/facebook_pages/models/1_cta_full_refresh/page_base.sql, dbt-cta/facebook_pages/models/1_cta_full_refresh/page_insights_base.sql, dbt-cta/facebook_pages/models/1_cta_full_refresh/post_base.sql, dbt-cta/facebook_pages/models/1_cta_full_refresh/post_insights_base.sql
We've done this for most/all other syncs, not sure if this was missed or reverted somehow but anyway it works locally and we need these to get tests to pass for re-enabled syncs so I'm gonna YOLO it in!
=> hotfix: add deduping CTEs to FB Pages sync

dbt-cta/blocks/models/0_ctes/registration_forms_ab2.sql
This succeeds locally. Gonna YOLO-merge this into prod to bring the sync back to life 👀 cc @huystuhh
=> hotfix (blocks): registration_type in registration_forms is now a string

dbt-cta/blocks/models/0_ctes/scans_qc_overview_ab2.sql
@emily-flambe fixed this field on another table a few weeks ago in [this PR](https://github.com/community-tech-alliance/dbt-cta/pull/338), but the same change is needed on the `scans_qc_overview` table now too.
=> hotfix (blocks): registration_type in scans_qc_overview is now a string

dbt-cta/thrutext/models/1_cta_incremental/daily_messages_base.sql, dbt-cta/thrutext/models/1_cta_incremental/daily_surveys_base.sql, dbt-cta/thrutext/models/1_cta_incremental/opt_outs_base.sql
This enables the dbt to run if columns are removed. Having this set to `add` only allows new columns to be added, but sometimes columns disappear in a Thrutext export.
=> thrutext: on_schema_change should be `sync_all_columns`

dbt-cta/hustle/models/0_ctes/tags_cte1.sql
The dbt was failing to create a `_cta_hashid` because there were optional fields included. This PR pares down the amount of columns that are used to create the `_cta_hashid` so it more faithfully will be created. This was tested locally and the test that was previously failing now passes.
=> hotfix: yeet unnecesary columns to create cta_hashid

dbt-cta/blocks_incremental/models/1_cta_incremental/vr_zips_lookup_base.sql
Our `blocks_incremental` dbt still contains CTEs and partner delivery models for `vr_zips_lookup`, but the `_base` model went missing. This hotfix adds the model back. I already made sure this runs successfully locally.
=> hotfix (blocks_incremental): bring back vr_zips_lookup_base

dbt-cta/echo19/models/1_cta_incremental/_1_cta_incremental__models.yml, dbt-cta/echo19/models/1_cta_incremental/clicks_base.sql, dbt-cta/echo19/models/1_cta_incremental/ivr_contact_base.sql, dbt-cta/echo19/models/1_cta_incremental/survey_result_base.sql, dbt-cta/echo19/models/1_cta_incremental/tag_result_base.sql, dbt-cta/echo19/models/1_cta_incremental/text_contact_base.sql
When checking for dupes in echo19 data, I found that the tables all have existing primary keys. We should use these as unique_key instead of hashids.
Also, the tests were missing a few tables, so I added tests for them and included uniqueness tests for the PKs in all tables.
(We don't have any dupes in this sync right now, everything is fine, but we should definitely at least add the tests in.)
=> echo19: use existing primary keys instead of hashid for deduping

dbt-cta/sprout_social/models/0_ctes/client_metadata_ab2.sql, dbt-cta/sprout_social/models/0_ctes/customer_groups_ab2.sql, dbt-cta/sprout_social/models/0_ctes/customer_profiles_ab2.sql, dbt-cta/sprout_social/models/0_ctes/customer_tags_ab2.sql, dbt-cta/sprout_social/models/0_ctes/customer_users_ab2.sql, dbt-cta/sprout_social/models/1_cta_incremental/_1_cta_incremental__models.yml, dbt-cta/sprout_social/models/1_cta_incremental/client_metadata_base.sql, dbt-cta/sprout_social/models/1_cta_incremental/customer_groups_base.sql, dbt-cta/sprout_social/models/1_cta_incremental/customer_profiles_base.sql, dbt-cta/sprout_social/models/1_cta_incremental/customer_tags_base.sql, dbt-cta/sprout_social/models/1_cta_incremental/customer_users_base.sql
similar to https://github.com/community-tech-alliance/dbt-cta/pull/399 , which did the same thing for echo19.
Some of the Sprout Social tables have existing primary keys that we should use for the unique_key rather than the hashids. This PR also adds non-null and uniqueness tests for those PKs.
=> sprout social should use existing primary keys for unique_key (+tests)

dbt-cta/snapchat_marketing/models/0_ctes/adaccounts_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/adaccounts_regulations_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/ads_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/ads_stats_daily_ab4.sql, dbt-cta/snapchat_marketing/models/0_ctes/adsquads_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/adsquads_skadnetwork_properties_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/adsquads_targeting_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/adsquads_targeting_geos_ab4.sql, dbt-cta/snapchat_marketing/models/0_ctes/campaigns_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/creatives_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/creatives_web_view_properties_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/media_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/organizations_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/organizations_configuration_settings_ab3.sql, dbt-cta/snapchat_marketing/models/0_ctes/segments_ab3.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/ad_stats_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/adaccounts_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/adaccounts_regulations_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/ads_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/adsquads_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/adsquads_skadnetwork_properties_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/adsquads_targeting_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/adsquads_targeting_geos_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/campaigns_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/creatives_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/creatives_web_view_properties_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/media_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/organizations_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/organizations_configuration_settings_base.sql, dbt-cta/snapchat_marketing/models/1_cta_incremental/segments_base.sql
Snapchat is one of our older syncs, so we hadn't yet gotten around to adding these CTEs to dedupe when there are dupe rows in the raw data (which recently has been the case for `segments`).
Ran this locally, seems fine ✅
=> feat: add deduping CTEs to snapchat models

.sqlfluff
For linting purposes, we can use jinja (instead of dbt) as the templater and tell it to ignore templating since we don't need sqlfluff to actually validate the queries and attempt to connect to the database (which is does by default with dbt). 
Using jinja is more lightweight and still does the lint formatting that we want sqlfluff to do for us!
I haven't been able to find any discrepancies between using dbt and jinja as the templator for our sql files in my testing.
=> feat: using jinja templater instead of dbt

.github/workflows/run_sqlfluff.yaml
Our SQLFluff lint tests work! Just changing the format from github-annotation so that it's easier to read for us Humans.
=> feat: changing format of sqlfluff to human readable

dbt-cta/hustle/models/0_ctes/inbox_messages_cte1.sql
Hustle added a new `status` field to their `inbox_messages` table. This PR is for that.
=> HOTFIX: add status field to inbox_messages table
