- dbt-cta/dbt_project.yml
- dbt-cta/mailchimp/models/1_cta_base/campaigns_base.sql
@jitoquinto fixing dbt_project.yml in prod so that the dbt operators work (we had already applied this change in dev, but I neglected to submit the change to this repo to make it official).
> fix: use correct dbt packages install path

- dbt-cta/Pipfile
- dbt-cta/Pipfile.lock
My python is scuffed so I have to do everything in an environment - seems like a fine thing to include in this repo, though!
Additional TODO(): add instructions on running dbt locally to utils/README.md 👀
> feat: add Pipfile and Pipfile.lock

- dbt-cta/mailchimp/models/3_partner_views/v_campaigns.sql
Reverts community-tech-alliance/dbt-cta#141
> Revert "SCIENCE (mailchimp only) - checking to see what prod deployment does, don't be alarmed [DE-231]"

- dbt-cta/dbt_project.yml
setting a reminder to merge this on Monday so if things go sideways we don't need to address over the weekend (cc @michaelefisher)
> Revert "feat: set auto_refresh to `false` for partner matviews"

- dbt-cta/dbt_project.yml
now that it's Monday let's give this a go once the syncs are all done (one remaining)
> un-reverting "feat: set auto_refresh to `false` for partner matviews"

- dbt-cta/monitoring/models/0_staging/meta/_meta__sources.yml
Companion PR in [airflow-dags](https://github.com/community-tech-alliance/airflow-dags/pull/285)
> [DE-328] Abstract sheet IDs to env vars

- dbt-cta/monitoring/models/1_intermediate/composer_logs/int_parse_scheduler_logs.sql
Quick follow up on #154, need to convert the timezones coming from the Composer logs to EST from UTC.
> [DE-338] Convert timezones on composer logs

- dbt-cta/monitoring/models/0_staging/meta/_meta__sources.yml
Gonna yolo-merge this because it's just documentation 👀
> docs (monitoring): add some explanatory words re: configured_syncs.json

- Pipfile
- Pipfile.lock
- utils/cta_dbt_helper.sh
- utils/generate_schema_yml.py
https://techallies.atlassian.net/browse/DE-410
Looks like the issue was just  `model_config in model_configs[0]:` It should've been accessing `model_config[0]`. 
I also did a bit of renaming and breaking out since some of the code was hard for me to understand haha
> fix: dbt tests generator add universal tests to all models

- dbt-cta/spoke_mo/models/1_cta_incremental/_1_cta_incremental__models.yml
- dbt-cta/spoke_mo/models/sources.yml
Creating tests for https://techallies.atlassian.net/browse/DE-387
Tests for all 21 dbs have been tested locally. This branch seeks to create dbt tests and finish up Phase 3 of a MoveOn-flavored Spoke sync for State Voices.
> feat: dbt tests for move on spoke

- dbt-cta/zoho_creator_meta/models/0_ctes/applications_ab1.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/applications_ab2.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/applications_ab3.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/fields_ab1.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/fields_ab2.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/fields_ab3.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/forms_ab1.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/forms_ab2.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/forms_ab3.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/pages_ab1.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/pages_ab2.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/pages_ab3.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/reports_ab1.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/reports_ab2.sql
- dbt-cta/zoho_creator_meta/models/0_ctes/reports_ab3.sql
- dbt-cta/zoho_creator_meta/models/1_cta_full_refresh/applications_base.sql
- dbt-cta/zoho_creator_meta/models/1_cta_full_refresh/fields_base.sql
- dbt-cta/zoho_creator_meta/models/1_cta_full_refresh/forms_base.sql
- dbt-cta/zoho_creator_meta/models/1_cta_full_refresh/pages_base.sql
- dbt-cta/zoho_creator_meta/models/1_cta_full_refresh/reports_base.sql
- dbt-cta/zoho_creator_meta/models/2_partner_matviews/applications.sql
- dbt-cta/zoho_creator_meta/models/2_partner_matviews/fields.sql
- dbt-cta/zoho_creator_meta/models/2_partner_matviews/forms.sql
- dbt-cta/zoho_creator_meta/models/2_partner_matviews/pages.sql
- dbt-cta/zoho_creator_meta/models/2_partner_matviews/reports.sql
- dbt-cta/zoho_creator_meta/models/sources.yml
https://techallies.atlassian.net/browse/DE-429
dbt for the new Zoho Creator connector! Note this is only for the Meta API Endpoints and not the Bulk endpoints
PR for full DAG which is also syncing Bulk Reports - https://github.com/community-tech-alliance/airflow-dags/pull/349
> feat: Init Zoho Creator dbt for Metadata portion of sync

- utils/dbt_format_utils.py
This is literally the tiniest thing and approximately does not matter but I want it to happen lol
> feat: make matview generator script not case sensitive

- dbt-cta/mobilize/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
- dbt-cta/mobilize/models/sources.yml
- utils/cta_dbt_helper.sh
@emily-flambe what do we do if we run tests and dev and find dupes 🙃 ?? Should i run in prod and see if its a problem there? 
Anyway, here are the dbt tests for mobilize! this is my first time doing this so let me know if I'm missing anything or if i did something wrong!
> feat: add mobilize dbt tests

- dbt-cta/adp_worker_management/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
- dbt-cta/adp_worker_management/models/sources.yml
cc @kanelouise , per [your comment on PR 199!](https://github.com/community-tech-alliance/dbt-cta/pull/199#issuecomment-1652103478)
tests passed on dev data when run locally 🙌
> feat (ADP): add `not_null` and `unique` tests for AssociateOID in `workers_base`

- dbt-cta/monitoring/models/1_intermediate/workflows_logs/int_workflow_logs.sql
Just a cute little fix that assigns `partner_name` to an execution_id for a workflow based on the first log emitted for the execution, since that log (but not the log when the execution completes) includes the JSON payload used to trigger the workflow, which is where we get `partner_name` when available.
Gonna yolo-merge this but happy to answer for my crimes if desired 👻
> hotfix (monitoring): use `partner_name` extracted from first log per workflow execution

- dbt-cta/monitoring/models/1_intermediate/workflows_logs/int_workflow_logs.sql
I think this must have literally been some random twitch of a finger while I was committing changes earlier!
> hotfix: typo

- dbt-cta/jazzhr/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
Part 1 of [DE-440](https://techallies.atlassian.net/browse/DE-440)
There are 4 tables that don't have great primary keys outside of `airbyte` added columns. Those columns are: hires, applicants, applicants_to_jobs, categories_to_applicants. All other tables have unique tests on `id`. 
All tests pass!
[DE-360]: https://techallies.atlassian.net/browse/DE-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DE-440]: https://techallies.atlassian.net/browse/DE-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DE 440 jazzhr dbt tests

- dbt-cta/action_network/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
Generated a models yaml file and added some appropriate tests to fields like `id` and `_airbyte_*_hasid`.
> adding yaml def and dbt tests for action_network full_refresh

- dbt-cta/packages.yml
@emily-flambe I forgot that I had done this in Dev already! but we will need to make this change in prod and update the dbt-package for elementary in prod GCS if we merge in the other PR bumping the python package
> [DE-480] feat: bump elementary dbt package

- dbt-cta/packages.yml
Reverts community-tech-alliance/dbt-cta#228
> Revert "[DE-480] feat: bump elementary dbt package"

- dbt-cta/packages.yml
Reverts community-tech-alliance/dbt-cta#231
Turns out our struggles were because of pyfiglet 🫠
> Revert "Revert "[DE-480] feat: bump elementary dbt package""

- dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_ab1.sql
- dbt-cta/usvote_foundation/models/0_ctes/offices_addresses_contacts_ab1.sql
- dbt-cta/usvote_foundation/models/0_ctes/offices_officials_ab1.sql
- dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_addresses_base.sql
- dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_addresses_contacts_base.sql
- dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_base.sql
- dbt-cta/usvote_foundation/models/1_cta_full_refresh/offices_officials_base.sql
- dbt-cta/usvote_foundation/models/1_cta_full_refresh/officials_base.sql
- dbt-cta/usvote_foundation/models/1_cta_full_refresh/regions_base.sql
- dbt-cta/usvote_foundation/models/1_cta_full_refresh/states_base.sql
`dbt run` is succeeding for me locally after making this fix. But how did the dbt ever succeed in the first place...?
> fix (usvotefoundation): fix upstream model references in models for nested data

- Pipfile
- Pipfile.lock
- dbt-cta/blocks/models/1_cta_full_refresh/_1_cta_full_refresh__models.yml
- dbt-cta/blocks/models/1_cta_incremental/_1_cta_incremental__models.yml
These yamls are already saved to GCS and the blocks DAG is proceeding successfully, so I won't merge this until BANDDE review (cc @jitoquinto @kanelouise @royconst )
> hotfix: regenerate schema yamls with new dbt version (unclear why this helped)

- dbt-cta/blocks/models/1_cta_incremental/ar_internal_metadata_base.sql
Ran locally, just checking in hotfix.
> hotfix: blocks hotkey ar_internal_metabase key -> hash

- dbt-cta/jazzhr/models/0_ctes/activities_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/applicants_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/applicants_to_jobs_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/categories_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/categories_to_applicants_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/contacts_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/hires_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/jobs_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/questionnaire_answers_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/tasks_ab4.sql
- dbt-cta/jazzhr/models/0_ctes/users_ab4.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/activities_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/applicants_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/applicants_to_jobs_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/categories_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/categories_to_applicants_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/contacts_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/hires_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/jobs_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/questionnaire_answers_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/tasks_base.sql
- dbt-cta/jazzhr/models/1_cta_full_refresh/users_base.sql
I've run this dbt locally to fix TOT's data in prod, but would love eyes on this before merging!
> fix: dedupe all jazzhr tables on `hashid`

- dbt-cta/dbt_project.yml
- dbt-cta/profiles.yml
** This has been manually deployed - do not merge me! **
> hotfix: no elementary for now

- dbt-cta/dbt_project.yml
Reverts community-tech-alliance/dbt-cta#301
> Revert "feat: enable `full_refresh` for partner models"

- dbt-cta/sprout_social/models/0_ctes/twitter_post_analytics_ab1.sql
- dbt-cta/sprout_social/models/0_ctes/twitter_post_analytics_ab2.sql
- dbt-cta/sprout_social/models/0_ctes/twitter_post_analytics_ab3.sql
- dbt-cta/sprout_social/models/0_ctes/twitter_profile_analytics_ab1.sql
- dbt-cta/sprout_social/models/0_ctes/twitter_profile_analytics_ab2.sql
- dbt-cta/sprout_social/models/0_ctes/twitter_profile_analytics_ab3.sql
- dbt-cta/sprout_social/models/1_cta_incremental/_1_cta_incremental__models.yml
- dbt-cta/sprout_social/models/1_cta_incremental/facebook_post_analytics_base.sql
- dbt-cta/sprout_social/models/1_cta_incremental/facebook_profile_analytics_base.sql
- dbt-cta/sprout_social/models/1_cta_incremental/instagram_post_analytics_base.sql
- dbt-cta/sprout_social/models/1_cta_incremental/instagram_profile_analytics_base.sql
- dbt-cta/sprout_social/models/1_cta_incremental/tiktok_post_analytics_base.sql
- dbt-cta/sprout_social/models/1_cta_incremental/tiktok_profile_analytics_base.sql
- dbt-cta/sprout_social/models/1_cta_incremental/twitter_post_analytics_base.sql
- dbt-cta/sprout_social/models/1_cta_incremental/twitter_profile_analytics_base.sql
- dbt-cta/sprout_social/models/2_cta_delivery/cta_twitter_post_analytics.sql
- dbt-cta/sprout_social/models/2_cta_delivery/cta_twitter_profile_analytics.sql
- dbt-cta/sprout_social/models/2_partner_matviews/twitter_post_analytics_mv.sql
- dbt-cta/sprout_social/models/2_partner_matviews/twitter_profile_analytics_mv.sql
- dbt-cta/sprout_social/models/sources.yml
> [DE-657] feat: add twitter models to sprout social

- dbt-cta/openfield/models/0_ctes/knock_conversation_code_cte2.sql
- dbt-cta/openfield/models/0_ctes/knock_people_cte1.sql
- dbt-cta/openfield/models/0_ctes/knock_people_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_attempts_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_celloptins_conversations_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_email_conversations_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_list_conversations_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_longtext_conversations_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_name_conversations_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_shorttext_conversations_cte2.sql
- dbt-cta/openfield/models/0_ctes/redshift_people_truefalse_conversations_cte2.sql
- dbt-cta/openfield/models/1_cta_full_refresh/knock_people_base.sql
Sibling PR [here](https://github.com/community-tech-alliance/airflow-dags/pull/765)
> Yeet `of_voter_file_id` from Openfield's knock_people table

- dbt-cta/openfield/models/0_ctes/knock_people_cte1.sql
- dbt-cta/openfield/models/1_cta_full_refresh/knock_people_base.sql
Once again... should be the last column update today 🤞. Sibling [PR here](https://github.com/community-tech-alliance/airflow-dags/compare/kane/openfield_airflow_knock_people_hotfix_2?expand=1)
> yeet alloy_uuid from knock_people table

- dbt-cta/hustle/models/0_ctes/tags_cte1.sql
- dbt-cta/hustle/models/0_ctes/tags_cte2.sql
- dbt-cta/hustle/models/1_cta_incremental/_1_cta_incremental__models.yml
- dbt-cta/hustle/models/1_cta_incremental/tags_base.sql
- dbt-cta/hustle/models/2_cta_delivery/cta_tags.sql
- dbt-cta/hustle/models/2_partner_matviews/tags.sql
- dbt-cta/hustle/models/sources.yml
Finishing out [this ticket](https://techallies.atlassian.net/browse/DE-752). The dbt ran locally and produced a tags table in the partner project without hiccups.
> feat: add tags stream to hustle sync

- dbt-cta/blocks_incremental/models/1_cta_incremental/vr_zips_lookup_base.sql
> hotfix: sad typo

- Pipfile
- Pipfile.lock
- dbt-cta/mobilize/models/2_partner_matviews/affiliations.sql
- dbt-cta/mobilize/models/2_partner_matviews/event_co_hosts.sql
- dbt-cta/mobilize/models/2_partner_matviews/event_tags.sql
- dbt-cta/mobilize/models/2_partner_matviews/events.sql
- dbt-cta/mobilize/models/2_partner_matviews/organizations.sql
- dbt-cta/mobilize/models/2_partner_matviews/participations.sql
- dbt-cta/mobilize/models/2_partner_matviews/sms_opt_ins.sql
- dbt-cta/mobilize/models/2_partner_matviews/timeslots.sql
- dbt-cta/mobilize/models/2_partner_matviews/users.sql
- dbt-cta/mobilize/models/2_partner_matviews/van_events.sql
- dbt-cta/mobilize/models/2_partner_matviews/van_locations.sql
- dbt-cta/mobilize/models/2_partner_matviews/van_persons.sql
- dbt-cta/mobilize/models/2_partner_matviews/van_shifts.sql
- dbt-cta/mobilize/models/2_partner_matviews/van_signups.sql
- upgrade python and dbt packages to reflect composer upgrade versions
- remove partition config from partner dbt for mobilize
> HOTFIX: Upgrade python, dbt, and fix mobilize partner dbt

- dbt-cta/ddx/README.md
- dbt-cta/ddx/models/0_ctes/contact_attempt_cte1.sql
- dbt-cta/ddx/models/0_ctes/contact_attempt_cte2.sql
- dbt-cta/ddx/models/1_cta_incremental/_1_cta_incremental__models.yml
- dbt-cta/ddx/models/1_cta_incremental/contact_attempt_base.sql
- dbt-cta/ddx/models/sources.yml
From [PAD-2819](https://techallies.atlassian.net/browse/PAD-2819?atlOrigin=eyJpIjoiYWFjOWM3NDI5YjA5NDVmZDljZjc1MDBhNWZmZTkzMmIiLCJwIjoiaiJ9)
[PAD-2819]: https://techallies.atlassian.net/browse/PAD-2819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: adding contact attempt for ddx
